# Generated by Django 4.2.3 on 2023-07-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_operational', models.BooleanField(default=True)),
                ('current_floor', models.PositiveIntegerField(default=1)),
                ('is_moving_up', models.BooleanField(default=False)),
                ('is_moving_down', models.BooleanField(default=False)),
                ('is_door_open', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_floor', models.PositiveIntegerField()),
                ('to_floor', models.PositiveIntegerField()),
                ('requested_time', models.DateTimeField(auto_now_add=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.elevator')),
            ],
        ),
    ]
