# Generated by Django 4.2.3 on 2023-07-21 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='elevator',
            name='last_floor',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='elevator',
            name='next_floor',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elevator',
            name='elevator_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.elevatorsystem'),
        ),
    ]
