# Generated by Django 4.2.3 on 2023-07-21 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_elevatorsystem_elevator_last_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='elevator_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.elevatorsystem'),
        ),
    ]
