# Generated by Django 4.2.3 on 2023-07-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_elevator_elevator_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='requested_time',
        ),
    ]
